var express = require('express');
var router = express.Router();

// This file is generated by express generator. It will be removed in the future
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });
});

module.exports = router;
